name       : intel-level-zero
version    : 1.10.0
release    : 6
source     :
    - https://github.com/oneapi-src/level-zero/archive/refs/tags/v1.10.0.tar.gz : 2811e4128ff6114020d0a147c2769b9b2e782e68ad49827685c33b9e716bf6ab
license    : MIT
component  : programming.library
homepage   : https://github.com/oneapi-src/level-zero/
summary    : oneAPI Level Zero Specification Headers and Loader
patterns   :
    - /*
description: |
    The oneAPI Level Zero (Level Zero) provides low-level direct-to-metal interfaces that are tailored to the devices in a oneAPI platform. This package includes the Level Zero headers, loader, and validation layer.
builddeps  :
    - opencl-headers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
