name       : intel-level-zero
version    : 1.4.1
release    : 2
source     :
    - https://github.com/oneapi-src/level-zero/archive/refs/tags/v1.4.1.tar.gz : 2878fa29cbf5cea677a00f6dde6eb42d147c98c8d2a99fefece284d85cd1476b
license    : MIT
component  : programming.library
homepage   : https://github.com/oneapi-src/level-zero/
summary    : oneAPI Level Zero Specification Headers and Loader
patterns   :
    - /*
description: |
    The oneAPI Level Zero (Level Zero) provides low-level direct-to-metal interfaces that are tailored to the devices in a oneAPI platform. This package includes the Level Zero headers, loader, and validation layer.
builddeps  :
    - opencl-headers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
